# Generated by Django 5.1.7 on 2025-04-01 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_variation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variation',
            name='variation_category',
            field=models.CharField(choices=[('gender', 'gender'), ('size', 'size')], max_length=100),
        ),
    ]
